CREATE table if not exists silver.employees (
client_employee_id VARCHAR(100) primary key,
first_name VARCHAR(255) not null,
middle_name	VARCHAR(255),
last_name VARCHAR(255) not null,
preferred_name VARCHAR(255),
job_code VARCHAR(100),
job_title VARCHAR(255),
job_start_date DATE,
organization_id	VARCHAR(255),
organization_name VARCHAR(255),
department_id VARCHAR(100),
department_name	VARCHAR(255),
dob	DATE,
hire_date DATE,
recent_hire_date DATE,
anniversary_date DATE,	
term_date DATE,
years_of_experience	NUMERIC(4,1),
work_email VARCHAR(255),
address	TEXT,
city VARCHAR(100),
state VARCHAR(100),
zip	VARCHAR(100),
country	VARCHAR(100),
manager_employee_id	VARCHAR(100),
manager_employee_name VARCHAR(255),
fte_status VARCHAR(100),
is_per_deim	BOOLEAN,
cell_phone VARCHAR(20),
work_phone VARCHAR(20),	
scheduled_weekly_hour INTEGER,
active_status BOOLEAN,
termination_reason TEXT,
clinical_level VARCHAR(255),
loaded_at TIMESTAMP NOT NULL,
source_file VARCHAR(500)
);